runtime: python37
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /app/static
  static_dir: static

- url: /.*
  script: auto

- url: /favicon\.ico
  static_files: app/static/images/favicon.ico
  upload: app/static/images/favicon\.ico

